;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
	'(
		 beginning-of-visual-line
		 c-electric-delete-forward
		 c-electric-semi&comma
		 cua-delete-region
		 end-of-visual-line
		 isearch-abort
		 isearch-backward-regexp
		 isearch-printing-char
		 overwrite-mode
		 smex
		 ))

(setq mc/cmds-to-run-once
	'(
		 cua-insert-char-rectangle
		 sgml-slash
		 ))
